INSERT INTO USERS (ID, PASSWORD, STATUS, USERNAME) VALUES(1, '$2a$10$4px.TAHtF9eJLpvIC6vds.ZV821SO2BLkieZnIqg0ETnWbDZ8wCNO', 1, 'admin');
INSERT INTO USERS (ID, PASSWORD, STATUS, USERNAME) VALUES(2, '$2a$10$0q7RybwIcJZkx4W0zOceQeLLSHFb9DIKyhMZ5XiJHg50oh9sVAPS2', 1, 'garlick');
INSERT INTO USERS (ID, PASSWORD, STATUS, USERNAME) VALUES(3, '$2a$10$L4FEjlvyVHvZ.VaphimWYeGSp/elccHJMm796MnszHyC63A3.n.Ve', 1, 'bu');
INSERT INTO USERS (ID, PASSWORD, STATUS, USERNAME) VALUES(4, '$2a$10$Im.WqA4KrjIEkOGlkKrbqOkvxrz2hjlyfBnMw9ZaHsPH9JEaSBS6C', 1, 'goku');

INSERT INTO ROLES (ID, NAME) VALUES(1, 'ROLE_ADMIN');
INSERT INTO ROLES (ID, NAME) VALUES(2, 'ROLE_USER');

INSERT INTO USERS_ROLES (USER_AUTH_ID, ROLES_ID) VALUES(1, 1);
INSERT INTO USERS_ROLES (USER_AUTH_ID, ROLES_ID) VALUES(2, 2);
INSERT INTO USERS_ROLES (USER_AUTH_ID, ROLES_ID) VALUES(3, 2);
INSERT INTO USERS_ROLES (USER_AUTH_ID, ROLES_ID) VALUES(4, 2);

INSERT INTO AIRCRAFT (ID, AVAILABLE, NAME) VALUES(1, 1, 'RCZD 789');
INSERT INTO AIRCRAFT (ID, AVAILABLE, NAME) VALUES(2, 1, 'Apolo');
INSERT INTO AIRCRAFT (ID, AVAILABLE, NAME) VALUES(3, 1, 'Apogalize 5369');
INSERT INTO AIRCRAFT (ID, AVAILABLE, NAME) VALUES(4, 1, 'Jupiter 51');
INSERT INTO AIRCRAFT (ID, AVAILABLE, NAME) VALUES(5, 1, 'Mate a la vista');

COMMIT;